# Generated with scripts/get_makefile_decls.py ESP32
BOARD=ESP32
PROJ_NAME=espruino_2v01_esp32
EMBEDDED=1
FAMILY=ESP32
CHIP=ESP32
OPTIMIZEFLAGS+=-Og
USE_ESP32?=1
USE_NET?=1
USE_GRAPHICS?=1
USE_CRYPTO?=1
USE_SHA256?=1
USE_SHA512?=1
USE_TLS?=1
USE_TELNET?=1
USE_NEOPIXEL?=1
USE_FILESYSTEM?=1
USE_FLASHFS?=1
USE_BLUETOOTH?=1
DEFINES+=-DESP_PLATFORM -DESP32=1
DEFINES+=-DJSVAR_MALLOC
